apiVersion: v1
kind: Secret
metadata:
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "redis_type" "embedded_redis"}}'
  name: sentry-redis
  labels:
    app: redis
type: Opaque
stringData:
  redis-password: '{{repl ConfigOption "embedded_redis_password"}}'
