apiVersion: v1
kind: Secret
metadata:
  name: sentry
  labels:
    app: sentry
type: Opaque
data:
  sentry-secret: '{{repl ConfigOption "secret_key" | Base64Encode}}'
  smtp-password: '{{repl ConfigOption "smtp_password" | Base64Encode}}'
  user-password: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  boolean-value: '{{repl LicenseFieldValue "ABoolean" | ParseBool}}'
