apiVersion: v1
kind: Secret
metadata:
  name: sentry
  labels:
    app: sentry
type: Opaque
stringData:
  sentry-secret: '{{repl ConfigOption "secret_key"}}'
  smtp-password: '{{repl ConfigOption "smtp_password"}}'
  user-password: '{{repl ConfigOption "admin_password"}}'
  boolean-value: '{{repl LicenseFieldValue "ABoolean" | ParseBool}}'
